services:
  taskmanager-postgres:
    image: postgres:18
    container_name: taskmanager-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TaskManagerDb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql

  taskmanager-api:
    build:
      context: .
      dockerfile: TaskManager/Dockerfile
    container_name: taskmanager-api
    depends_on:
      - taskmanager-postgres
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSql=Host=taskmanager-postgres;Port=5432;Database=TaskManagerDb;Username=postgres;Password=postgres
    command: ["dotnet", "TaskManager.dll"]
