services:
  postgres-taskmanager:
    image: postgres:18
    container_name: postgres-taskmanager
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TaskManagerDb
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql
